// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdGDKz_FOXubxTuf4_3qVZXGm7lc0HPeI',
    appId: '1:403944478838:web:0be7b2324e54e8111d6757',
    messagingSenderId: '403944478838',
    projectId: 'unwind-test',
    authDomain: 'unwind-test.firebaseapp.com',
    storageBucket: 'unwind-test.appspot.com',
    measurementId: 'G-61J1RMWJBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA83lBV2vV1GVfL5A_0LVFE6Dk083bj8-M',
    appId: '1:403944478838:android:b08287aa7a2b2cd31d6757',
    messagingSenderId: '403944478838',
    projectId: 'unwind-test',
    storageBucket: 'unwind-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfbldpv9CumPkNVv9-YSEI9IEuQ9C_zCM',
    appId: '1:403944478838:ios:35b7c906f81050331d6757',
    messagingSenderId: '403944478838',
    projectId: 'unwind-test',
    storageBucket: 'unwind-test.appspot.com',
    iosClientId: '403944478838-q1vata3157m4b582715igbndthvjfvnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfbldpv9CumPkNVv9-YSEI9IEuQ9C_zCM',
    appId: '1:403944478838:ios:35b7c906f81050331d6757',
    messagingSenderId: '403944478838',
    projectId: 'unwind-test',
    storageBucket: 'unwind-test.appspot.com',
    iosClientId: '403944478838-q1vata3157m4b582715igbndthvjfvnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.test1',
  );
}
